name: BitBanged.com has been updated.
on:
  - push
  - repository_dispatch

jobs:
  update-readme:
    name: Update README.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Add recent blog posts.
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: https://bitbanged.com/authors/utkarsh/posts/index.xml
          comment_tag_name: BLOG-POSTS
          commit_message: Add recent blog posts.
      - name: Add recent projects.
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: https://bitbanged.com/authors/utkarsh/projects/index.xml
          comment_tag_name: PROJECTS
          commit_message: Add recent projects.
